package com.stud.Student.Management.dto;

import com.stud.Student.Management.entity.Course;
import lombok.Data;

import java.time.LocalDate;
import java.util.List;

@Data
public class StudentDTO {

    private Long id;
    private String name;
    private String email;

    private LocalDate dob;
    private AcademyDTO academy;
    private CourseDTO course;

    private Long academyId; // To link with the Academy entity
    private Long courseId; // To link with the Course entity
    private List<Course> courses; // Assuming a student can have multiple courses, using an array for simplicity


    // Constructors, getters, and setters can be generated by Lombok
}
